version: '3.5'

services:
  postgresql:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
    ports:
        - 5432:5432

  rabbitmq:
    image: rabbitmq:3.8.3-management
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - $PWD/storage/rabbitmq1:/var/lib/rabbitmq
    environment:
      - RABBITMQ_ERLANG_COOKIE=This_is_my_secret_phrase
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
volumes:
  postgresql:
  rabbitmq:
